#include "CommonPch.h"
#include "CodeGenerator.h"

CodeGenerator::CodeGenerator( const SchemaNode& schema, const TypeRegistry& types ) noexcept
	: _schema{ schema }
	, _type{ types }
	, _hasError{ false }
{

}

std::string CodeGenerator::generatePacketHeader( void ) noexcept
{
	std::ostringstream out;

	writeFileHeader( out );
	writePacketIdEnum( out );

	for ( const PacketNode& packet : _schema._packets )
	{
		writePacketStruct( out, packet );
		if ( true == _hasError )
		{
			return "";
		}
	}

	return out.str();
}

bool CodeGenerator::hasError( void ) const noexcept
{
	return _hasError;
}

const std::string& CodeGenerator::errorMessage( void ) const noexcept
{
	return _errorMessage;
}

void CodeGenerator::writeFileHeader( std::ostringstream& out ) const noexcept
{
	out << "//================================================================================\n";
	out << "// 이 파일은 idlc가 자동 생성했습니다. 직접 수정하지 마세요.\n";
	out << "// (This file is auto-generated by idlc. Do not edit.)\n";
	out << "//================================================================================\n";
	out << "#pragma once\n";
	out << "\n";
	out << "#include <cstdint>\n";
	out << "#include <string>\n";
	out << "\n";
}

void CodeGenerator::writePacketIdEnum( std::ostringstream& out ) const noexcept
{
	out << "enum class PacketId : int16_t\n";
	out << "{\n";
	out << "\tNONE = 0,\n";

	for ( const PacketNode& packet : _schema._packets )
	{
		out << "\t" << packet._name << " = " << packet._id << ",\n";
	}

	out << "};\n";
	out << "\n";
}

void CodeGenerator::writePacketStruct( std::ostringstream& out, const PacketNode& packet ) noexcept
{
	out << "#pragma pack( push, 1 )\n";
	out << "struct " << packet._name << "\n";
	out << "{\n";

	for ( const FieldNode& field : packet._fields )
	{
		const TypeInfo* info								= _type.find( field._type );
		if ( nullptr == info )
		{
			char buffer[ 256 ];
			snprintf( buffer, sizeof( buffer ), "패킷 '%s'의 필드 '%s': 알 수 없는 타입 '%s'", packet._name.c_str(), field._name.c_str(), field._type.c_str() );

			recordError( buffer );
			return;
		}

		out << "\t" << info->_cppType << " " << field._name << ";\n";
	}

	out << "};\n";
	out << "#pragma pack( pop )\n";
	out << "\n";
}

void CodeGenerator::recordError( const std::string& message ) noexcept
{
	if ( true == _hasError )
	{
		return;
	}

	_hasError												= true;
	_errorMessage											= message;
}
